Develop
lukerspace/Origin-Repository pull request #4
Opened 2021-04-23 17:30 UTC by lukerspace

新增app.py中 attractions/page以及attraction/id
新增sql.py
新增database.py

謝明承

2021-04-23 20:42 UTC, cwpeng requested changes
請提供已經上線，可以測試的 API 網址哦 ~

2021-04-23 20:59 UTC, lukerspace commented
更改網址

2021-04-23 20:59 UTC, cwpeng requested changes
要把上線的網址寫在訊息中哦，例如：
http://33.33.33.33:3000/api/attractions?page=0

這樣的點開就能看到結果。

2021-04-24 15:41 UTC, lukerspace commented
http://54.254.130.122:3000/api/attractions?page=2
http://54.254.130.122:3000/api/attractions?page=2&keyword=%E5%8F%B0%E5%8C%97101
http://54.254.130.122:3000/api/attraction/66

麻煩老師了

2021-04-24 16:52 UTC, cwpeng requested changes
我們的 keyword 會對景點名稱做關鍵字搜尋，也就是只要名稱中包含關鍵字就算數，不用完全一樣，搜尋結果也要做分頁的處理。

例如，搜尋臺北，就應該要有好幾頁的結果，並做分頁處理：
http://54.254.130.122:3000/api/attractions?page=0&keyword=臺北
http://54.254.130.122:3000/api/attractions?page=1&keyword=臺北

2021-04-25 02:47 UTC, lukerspace commented
http://54.254.130.122:3000/api/attractions?page=0&keyword=%E5%8F%B0%E5%8C%97
http://54.254.130.122:3000/api/attractions?page=20
http://54.254.130.122:3000/api/attraction/10

2021-04-25 06:17 UTC, cwpeng requested changes
伺服器連不上，無法測試 ~

2021-04-25 11:33 UTC, lukerspace commented
已重啟伺服器，請老師隨時查驗。謝謝

2021-04-25 12:46 UTC, cwpeng approved these changes
Good Work. ~

2021-04-25 12:55 UTC, merged